apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9153"
  labels:
    k8s-app: coredns
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    k8s-app: coredns
  ipFamilyPolicy: PreferDualStack
  clusterIP: ${cluster_dns_service_ips[0]}
  clusterIPs:
    %{~ for ip in cluster_dns_service_ips ~}
    - ${ip}
    %{~ endfor ~}
  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
